[2018-11-09 22:42:11,683] {models.py:1335} INFO - Dependencies all met for <TaskInstance: naveed_test.sleep 2018-11-10T05:10:00+00:00 [queued]>
[2018-11-09 22:42:11,703] {models.py:1335} INFO - Dependencies all met for <TaskInstance: naveed_test.sleep 2018-11-10T05:10:00+00:00 [queued]>
[2018-11-09 22:42:11,703] {models.py:1547} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 1
--------------------------------------------------------------------------------

[2018-11-09 22:42:11,718] {models.py:1569} INFO - Executing <Task(BashOperator): sleep> on 2018-11-10T05:10:00+00:00
[2018-11-09 22:42:11,718] {base_task_runner.py:124} INFO - Running: ['bash', '-c', u'airflow run naveed_test sleep 2018-11-10T05:10:00+00:00 --job_id 4 --raw -sd DAGS_FOLDER/test.py --cfg_path /var/folders/zk/29b_jkbx6z58gzz4zv4tzd_40000gn/T/tmprqgRGG']
[2018-11-09 22:42:14,862] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:14,861] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=3600
[2018-11-09 22:42:14,904] {base_task_runner.py:107} INFO - Job 4: Subtask sleep /Users/naveed/anaconda2/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2018-11-09 22:42:14,904] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   """)
[2018-11-09 22:42:15,190] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,189] {__init__.py:51} INFO - Using executor LocalExecutor
[2018-11-09 22:42:15,335] {base_task_runner.py:107} INFO - Job 4: Subtask sleep /Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py:1595: DeprecationWarning: The celeryd_concurrency option in [celery] has been renamed to worker_concurrency - the old setting has been used, but please update your config.
[2018-11-09 22:42:15,335] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   default=conf.get('celery', 'worker_concurrency')),
[2018-11-09 22:42:15,405] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option bind_user does not exist in the config!
[2018-11-09 22:42:15,405] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option search_scope does not exist in the config!
[2018-11-09 22:42:15,406] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option basedn does not exist in the config!
[2018-11-09 22:42:15,406] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option group_member_attr does not exist in the config!
[2018-11-09 22:42:15,406] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option uri does not exist in the config!
[2018-11-09 22:42:15,406] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option data_profiler_filter does not exist in the config!
[2018-11-09 22:42:15,407] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option bind_password does not exist in the config!
[2018-11-09 22:42:15,407] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option cacert does not exist in the config!
[2018-11-09 22:42:15,407] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option user_filter does not exist in the config!
[2018-11-09 22:42:15,407] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,405] {cli.py:464} ERROR - Section ldap Option user_name_attr does not exist in the config!
[2018-11-09 22:42:15,407] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section ldap Option superuser_filter does not exist in the config!
[2018-11-09 22:42:15,408] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section atlas Option username does not exist in the config!
[2018-11-09 22:42:15,408] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section atlas Option host does not exist in the config!
[2018-11-09 22:42:15,408] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section atlas Option password does not exist in the config!
[2018-11-09 22:42:15,408] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section atlas Option port does not exist in the config!
[2018-11-09 22:42:15,409] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section atlas Option sasl_enabled does not exist in the config!
[2018-11-09 22:42:15,409] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section kubernetes Option logs_volume_subpath does not exist in the config!
[2018-11-09 22:42:15,409] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section kubernetes Option git_repo does not exist in the config!
[2018-11-09 22:42:15,409] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,406] {cli.py:464} ERROR - Section kubernetes Option git_user does not exist in the config!
[2018-11-09 22:42:15,410] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option worker_container_repository does not exist in the config!
[2018-11-09 22:42:15,410] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option image_pull_secrets does not exist in the config!
[2018-11-09 22:42:15,410] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option git_sync_container_tag does not exist in the config!
[2018-11-09 22:42:15,410] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option in_cluster does not exist in the config!
[2018-11-09 22:42:15,411] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option namespace does not exist in the config!
[2018-11-09 22:42:15,411] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option dags_volume_subpath does not exist in the config!
[2018-11-09 22:42:15,411] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option git_sync_init_container_name does not exist in the config!
[2018-11-09 22:42:15,411] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option dags_volume_claim does not exist in the config!
[2018-11-09 22:42:15,412] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option git_subpath does not exist in the config!
[2018-11-09 22:42:15,412] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option worker_service_account_name does not exist in the config!
[2018-11-09 22:42:15,412] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,407] {cli.py:464} ERROR - Section kubernetes Option git_branch does not exist in the config!
[2018-11-09 22:42:15,412] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option logs_volume_claim does not exist in the config!
[2018-11-09 22:42:15,413] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option gcp_service_account_keys does not exist in the config!
[2018-11-09 22:42:15,413] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option airflow_configmap does not exist in the config!
[2018-11-09 22:42:15,413] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option git_sync_container_repository does not exist in the config!
[2018-11-09 22:42:15,413] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option worker_container_tag does not exist in the config!
[2018-11-09 22:42:15,414] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option git_password does not exist in the config!
[2018-11-09 22:42:15,414] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section kubernetes Option delete_worker_pods does not exist in the config!
[2018-11-09 22:42:15,414] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,408] {cli.py:464} ERROR - Section lineage Option backend does not exist in the config!
[2018-11-09 22:42:15,414] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section hive Option default_hive_mapred_queue does not exist in the config!
[2018-11-09 22:42:15,415] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section dask Option cluster_address does not exist in the config!
[2018-11-09 22:42:15,415] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section dask Option tls_cert does not exist in the config!
[2018-11-09 22:42:15,415] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section dask Option tls_key does not exist in the config!
[2018-11-09 22:42:15,416] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section dask Option tls_ca does not exist in the config!
[2018-11-09 22:42:15,416] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_host does not exist in the config!
[2018-11-09 22:42:15,416] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_log_id_template does not exist in the config!
[2018-11-09 22:42:15,417] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,409] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_end_of_log_mark does not exist in the config!
[2018-11-09 22:42:15,417] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,413] {models.py:258} INFO - Filling up the DagBag from /Users/naveed/Mira/hackathon/airflow/dags/test.py
[2018-11-09 22:42:15,483] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,482] {example_kubernetes_operator.py:54} WARNING - Could not import KubernetesPodOperator: No module named kubernetes
[2018-11-09 22:42:15,483] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,482] {example_kubernetes_operator.py:55} WARNING - Install kubernetes dependencies with:     pip install airflow['kubernetes']
[2018-11-09 22:42:15,654] {base_task_runner.py:107} INFO - Job 4: Subtask sleep [2018-11-09 22:42:15,653] {cli.py:492} INFO - Running <TaskInstance: naveed_test.sleep 2018-11-10T05:10:00+00:00 [running]> on host naveeds-MacBook-Pro.local
[2018-11-09 22:42:15,704] {bash_operator.py:74} INFO - Tmp dir root location: 
 /var/folders/zk/29b_jkbx6z58gzz4zv4tzd_40000gn/T
[2018-11-09 22:42:15,706] {bash_operator.py:87} INFO - Temporary script location: /var/folders/zk/29b_jkbx6z58gzz4zv4tzd_40000gn/T/airflowtmpZPCeRx/sleep3Xw1Rr
[2018-11-09 22:42:15,707] {bash_operator.py:97} INFO - Running command: sleep 60 && echo "done!"
[2018-11-09 22:42:15,713] {bash_operator.py:106} INFO - Output:
[2018-11-09 22:42:41,732] {logging_mixin.py:95} INFO - [2018-11-09 22:42:41,731] {jobs.py:2680} WARNING - State of this instance has been externally set to shutdown. Taking the poison pill.

[2018-11-09 22:42:41,774] {helpers.py:240} INFO - Sending 15 to GPID 3989
[2018-11-09 22:42:41,775] {models.py:1610} ERROR - Received SIGTERM. Terminating subprocesses.
[2018-11-09 22:42:41,775] {bash_operator.py:124} INFO - Sending SIGTERM signal to bash process group
[2018-11-09 22:42:41,797] {models.py:1736} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1633, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 108, in execute
    for line in iter(sp.stdout.readline, b''):
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1612, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
AirflowException: Task received SIGTERM signal
[2018-11-09 22:42:41,800] {models.py:1764} INFO - Marking task as FAILED.
[2018-11-09 22:42:41,832] {base_task_runner.py:107} INFO - Job 4: Subtask sleep Traceback (most recent call last):
[2018-11-09 22:42:41,833] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/bin/airflow", line 32, in <module>
[2018-11-09 22:42:41,834] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     args.func(args)
[2018-11-09 22:42:41,834] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2018-11-09 22:42:41,834] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     return f(*args, **kwargs)
[2018-11-09 22:42:41,835] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py", line 498, in run
[2018-11-09 22:42:41,835] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     _run(args, dag, ti)
[2018-11-09 22:42:41,835] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py", line 402, in _run
[2018-11-09 22:42:41,836] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     pool=args.pool,
[2018-11-09 22:42:41,836] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2018-11-09 22:42:41,836] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     return func(*args, **kwargs)
[2018-11-09 22:42:41,837] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1633, in _run_raw_task
[2018-11-09 22:42:41,837] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     result = task_copy.execute(context=context)
[2018-11-09 22:42:41,838] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 108, in execute
[2018-11-09 22:42:41,838] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     for line in iter(sp.stdout.readline, b''):
[2018-11-09 22:42:41,838] {base_task_runner.py:107} INFO - Job 4: Subtask sleep   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1612, in signal_handler
[2018-11-09 22:42:41,839] {base_task_runner.py:107} INFO - Job 4: Subtask sleep     raise AirflowException("Task received SIGTERM signal")
[2018-11-09 22:42:41,839] {base_task_runner.py:107} INFO - Job 4: Subtask sleep airflow.exceptions.AirflowException: Task received SIGTERM signal
[2018-11-09 22:42:41,911] {helpers.py:230} INFO - Process psutil.Process(pid=4014 (terminated)) (4014) terminated with exit code None
[2018-11-09 22:42:41,911] {helpers.py:230} INFO - Process psutil.Process(pid=4016 (terminated)) (4016) terminated with exit code None
[2018-11-09 22:42:41,966] {helpers.py:230} INFO - Process psutil.Process(pid=3989 (terminated)) (3989) terminated with exit code 1
[2018-11-09 22:42:41,967] {logging_mixin.py:95} INFO - [2018-11-09 22:42:41,966] {jobs.py:2612} INFO - Task exited with return code 0

