[2018-11-10 13:19:07,892] {models.py:1335} INFO - Dependencies all met for <TaskInstance: naveed_test.breakpoint_sensor_run_this_last_parallel 2018-11-10T19:10:00+00:00 [queued]>
[2018-11-10 13:19:07,900] {models.py:1335} INFO - Dependencies all met for <TaskInstance: naveed_test.breakpoint_sensor_run_this_last_parallel 2018-11-10T19:10:00+00:00 [queued]>
[2018-11-10 13:19:07,901] {models.py:1547} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 1
--------------------------------------------------------------------------------

[2018-11-10 13:19:07,960] {models.py:1569} INFO - Executing <Task(BreakPointSensor): breakpoint_sensor_run_this_last_parallel> on 2018-11-10T19:10:00+00:00
[2018-11-10 13:19:07,961] {base_task_runner.py:124} INFO - Running: ['bash', '-c', u'airflow run naveed_test breakpoint_sensor_run_this_last_parallel 2018-11-10T19:10:00+00:00 --job_id 156 --raw -sd DAGS_FOLDER/test.py --cfg_path /var/folders/zk/29b_jkbx6z58gzz4zv4tzd_40000gn/T/tmp9JD1K4']
[2018-11-10 13:19:10,788] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:10,788] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=3600
[2018-11-10 13:19:10,810] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel /Users/naveed/anaconda2/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2018-11-10 13:19:10,811] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   """)
[2018-11-10 13:19:10,992] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:10,991] {__init__.py:51} INFO - Using executor LocalExecutor
[2018-11-10 13:19:11,087] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel /Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py:1595: DeprecationWarning: The celeryd_concurrency option in [celery] has been renamed to worker_concurrency - the old setting has been used, but please update your config.
[2018-11-10 13:19:11,087] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   default=conf.get('celery', 'worker_concurrency')),
[2018-11-10 13:19:11,147] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option bind_user does not exist in the config!
[2018-11-10 13:19:11,148] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option search_scope does not exist in the config!
[2018-11-10 13:19:11,148] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option basedn does not exist in the config!
[2018-11-10 13:19:11,148] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option group_member_attr does not exist in the config!
[2018-11-10 13:19:11,148] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option uri does not exist in the config!
[2018-11-10 13:19:11,149] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option data_profiler_filter does not exist in the config!
[2018-11-10 13:19:11,149] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,147] {cli.py:464} ERROR - Section ldap Option bind_password does not exist in the config!
[2018-11-10 13:19:11,149] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section ldap Option cacert does not exist in the config!
[2018-11-10 13:19:11,149] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section ldap Option user_filter does not exist in the config!
[2018-11-10 13:19:11,149] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section ldap Option user_name_attr does not exist in the config!
[2018-11-10 13:19:11,150] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section ldap Option superuser_filter does not exist in the config!
[2018-11-10 13:19:11,150] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section atlas Option username does not exist in the config!
[2018-11-10 13:19:11,150] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section atlas Option host does not exist in the config!
[2018-11-10 13:19:11,150] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section atlas Option password does not exist in the config!
[2018-11-10 13:19:11,150] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section atlas Option port does not exist in the config!
[2018-11-10 13:19:11,151] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,148] {cli.py:464} ERROR - Section atlas Option sasl_enabled does not exist in the config!
[2018-11-10 13:19:11,151] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option logs_volume_subpath does not exist in the config!
[2018-11-10 13:19:11,151] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option git_repo does not exist in the config!
[2018-11-10 13:19:11,151] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option git_user does not exist in the config!
[2018-11-10 13:19:11,152] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option worker_container_repository does not exist in the config!
[2018-11-10 13:19:11,152] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option image_pull_secrets does not exist in the config!
[2018-11-10 13:19:11,152] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option git_sync_container_tag does not exist in the config!
[2018-11-10 13:19:11,152] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option in_cluster does not exist in the config!
[2018-11-10 13:19:11,153] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option namespace does not exist in the config!
[2018-11-10 13:19:11,153] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option dags_volume_subpath does not exist in the config!
[2018-11-10 13:19:11,153] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option git_sync_init_container_name does not exist in the config!
[2018-11-10 13:19:11,153] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option dags_volume_claim does not exist in the config!
[2018-11-10 13:19:11,153] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,149] {cli.py:464} ERROR - Section kubernetes Option git_subpath does not exist in the config!
[2018-11-10 13:19:11,154] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option worker_service_account_name does not exist in the config!
[2018-11-10 13:19:11,154] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option git_branch does not exist in the config!
[2018-11-10 13:19:11,154] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option logs_volume_claim does not exist in the config!
[2018-11-10 13:19:11,154] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option gcp_service_account_keys does not exist in the config!
[2018-11-10 13:19:11,154] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option airflow_configmap does not exist in the config!
[2018-11-10 13:19:11,155] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option git_sync_container_repository does not exist in the config!
[2018-11-10 13:19:11,155] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option worker_container_tag does not exist in the config!
[2018-11-10 13:19:11,155] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option git_password does not exist in the config!
[2018-11-10 13:19:11,155] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,150] {cli.py:464} ERROR - Section kubernetes Option delete_worker_pods does not exist in the config!
[2018-11-10 13:19:11,156] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section lineage Option backend does not exist in the config!
[2018-11-10 13:19:11,156] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section hive Option default_hive_mapred_queue does not exist in the config!
[2018-11-10 13:19:11,156] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section dask Option cluster_address does not exist in the config!
[2018-11-10 13:19:11,156] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section dask Option tls_cert does not exist in the config!
[2018-11-10 13:19:11,156] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section dask Option tls_key does not exist in the config!
[2018-11-10 13:19:11,157] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section dask Option tls_ca does not exist in the config!
[2018-11-10 13:19:11,157] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_host does not exist in the config!
[2018-11-10 13:19:11,157] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,151] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_log_id_template does not exist in the config!
[2018-11-10 13:19:11,157] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,152] {cli.py:464} ERROR - Section elasticsearch Option elasticsearch_end_of_log_mark does not exist in the config!
[2018-11-10 13:19:11,158] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,155] {models.py:258} INFO - Filling up the DagBag from /Users/naveed/Mira/hackathon/airflow/dags/test.py
[2018-11-10 13:19:11,223] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,223] {example_kubernetes_operator.py:54} WARNING - Could not import KubernetesPodOperator: No module named kubernetes
[2018-11-10 13:19:11,224] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,223] {example_kubernetes_operator.py:55} WARNING - Install kubernetes dependencies with:     pip install airflow['kubernetes']
[2018-11-10 13:19:11,364] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel [2018-11-10 13:19:11,364] {cli.py:492} INFO - Running <TaskInstance: naveed_test.breakpoint_sensor_run_this_last_parallel 2018-11-10T19:10:00+00:00 [running]> on host naveeds-MacBook-Pro.local
[2018-11-10 13:25:03,798] {helpers.py:240} INFO - Sending 15 to GPID 60970
[2018-11-10 13:25:03,799] {models.py:1610} ERROR - Received SIGTERM. Terminating subprocesses.
[2018-11-10 13:25:03,813] {models.py:1736} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1633, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/sensors/base_sensor_operator.py", line 78, in execute
    sleep(self.poke_interval)
  File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1612, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
AirflowException: Task received SIGTERM signal
[2018-11-10 13:25:03,815] {models.py:1764} INFO - Marking task as FAILED.
[2018-11-10 13:25:03,873] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel Traceback (most recent call last):
[2018-11-10 13:25:03,873] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/bin/airflow", line 32, in <module>
[2018-11-10 13:25:03,874] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     args.func(args)
[2018-11-10 13:25:03,874] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2018-11-10 13:25:03,874] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     return f(*args, **kwargs)
[2018-11-10 13:25:03,874] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py", line 498, in run
[2018-11-10 13:25:03,874] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     _run(args, dag, ti)
[2018-11-10 13:25:03,875] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/bin/cli.py", line 402, in _run
[2018-11-10 13:25:03,875] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     pool=args.pool,
[2018-11-10 13:25:03,875] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2018-11-10 13:25:03,875] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     return func(*args, **kwargs)
[2018-11-10 13:25:03,876] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1633, in _run_raw_task
[2018-11-10 13:25:03,876] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     result = task_copy.execute(context=context)
[2018-11-10 13:25:03,876] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/sensors/base_sensor_operator.py", line 78, in execute
[2018-11-10 13:25:03,876] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     sleep(self.poke_interval)
[2018-11-10 13:25:03,877] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel   File "/Users/naveed/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 1612, in signal_handler
[2018-11-10 13:25:03,877] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel     raise AirflowException("Task received SIGTERM signal")
[2018-11-10 13:25:03,877] {base_task_runner.py:107} INFO - Job 156: Subtask breakpoint_sensor_run_this_last_parallel airflow.exceptions.AirflowException: Task received SIGTERM signal
[2018-11-10 13:25:03,940] {helpers.py:230} INFO - Process psutil.Process(pid=60970 (terminated)) (60970) terminated with exit code 1
